### ISSUE TITLE
Flask-Track-Usage cannot be installed due to a versionConflict issue.

### ISSUE THREAD

**Issue by josephdong8088** [ashcrow/flask-track-usage#67]
Since 1/9/2023, I have been experiencing an issue when deploying a web application, of which the "Flask-Track-Usage" is one of the dependencies. During the deployment process, I am repeatedly encountering a failure at the step of installing this library, as shown in the output from the deployment via VS Code below. It appears that the issue is related to a version conflict, although all of the dependencies prior to this library were version-locked and there were no issues until yesterday. I would be very grateful for any assistance or advice in resolving this issue.
------------------
11:24:33 AM tlbu0: Starting deployment... 11:24:37 AM tlbu0: Creating zip package... 11:25:41 AM tlbu0: Zip package size: 114 MB 11:25:45 AM tlbu0: Fetching changes. 11:25:46 AM tlbu0: Cleaning up temp folders from previous zip deployments and extracting pushed zip file /tmp/zipdeploy/6381c077-ced4-486e-84c2-d342c83765f6.zip (109.68 MB) to /tmp/zipdeploy/extracted 11:26:10 AM tlbu0: Updating submodules. 11:26:11 AM tlbu0: Preparing deployment for commit id '2dbd1d48-8'. 11:26:11 AM tlbu0: PreDeployment: context.CleanOutputPath False 11:26:11 AM tlbu0: PreDeployment: context.OutputPath /home/site/wwwroot 11:26:11 AM tlbu0: Repository path is /tmp/zipdeploy/extracted 11:26:12 AM tlbu0: Running oryx build... 11:26:12 AM tlbu0: Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform python --platform-version 3.9 -p virtualenv_name=antenv --log-file /tmp/build-debug.log -i /tmp/8daf32fc4bbb7d4 --compress-destination-dir | tee /tmp/oryx-build.log 11:26:14 AM tlbu0: Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx 11:26:14 AM tlbu0: You can report issues at https://github.com/Microsoft/Oryx/issues 11:26:14 AM tlbu0: Oryx Version: 0.2.20220812.1, Commit: cdf6b1bef165d05b94830e963646495967d938f4, ReleaseTagName: 20220812.1 11:26:14 AM tlbu0: Build Operation ID: |6Hk8mpxbdvw=.571f5390_ 11:26:14 AM tlbu0: Repository Commit : 2dbd1d48-8e7b-4105-8556-33be450f2243 11:26:14 AM tlbu0: Detecting platforms... 11:26:16 AM tlbu0: Detected following platforms: 11:26:16 AM tlbu0: nodejs: 14.19.1 11:26:16 AM tlbu0: python: 3.9.16 11:26:16 AM tlbu0: Version '14.19.1' of platform 'nodejs' is not installed. Generating script to install it... 11:26:16 AM tlbu0: Version '3.9.16' of platform 'python' is not installed. Generating script to install it... 11:26:18 AM tlbu0: Using intermediate directory '/tmp/8daf32fc4bbb7d4'. 11:26:18 AM tlbu0: Copying files to the intermediate directory... 11:26:35 AM tlbu0: Done in 18 sec(s). 11:26:35 AM tlbu0: Source directory : /tmp/8daf32fc4bbb7d4 11:26:35 AM tlbu0: Destination directory: /home/site/wwwroot 11:26:35 AM tlbu0: Downloading and extracting 'nodejs' version '14.19.1' to '/tmp/oryx/platforms/nodejs/14.19.1'... 11:26:40 AM tlbu0: Downloaded in 5 sec(s). 11:26:40 AM tlbu0: Verifying checksum... 11:26:40 AM tlbu0: Extracting contents... 11:26:44 AM tlbu0: performing sha512 checksum for: nodejs... 11:26:44 AM tlbu0: Done in 9 sec(s). 11:26:44 AM tlbu0: Downloading and extracting 'python' version '3.9.16' to '/tmp/oryx/platforms/python/3.9.16'... 11:26:46 AM tlbu0: Downloaded in 2 sec(s). 11:26:46 AM tlbu0: Verifying checksum... 11:26:47 AM tlbu0: Extracting contents... 11:26:52 AM tlbu0: performing sha512 checksum for: python... 11:26:55 AM tlbu0: Done in 11 sec(s). 11:26:55 AM tlbu0: Python Version: /tmp/oryx/platforms/python/3.9.16/bin/python3.9 11:26:55 AM tlbu0: Creating directory for command manifest file if it does not exist 11:26:55 AM tlbu0: Removing existing manifest file 11:26:57 AM tlbu0: Python Virtual Environment: antenv 11:26:57 AM tlbu0: Creating virtual environment... 11:27:10 AM tlbu0: Activating virtual environment... 11:27:10 AM tlbu0: Running pip install... 11:27:41 AM tlbu0: [17:27:12+0000] Collecting requests==2.22.0 11:27:41 AM tlbu0: [17:27:12+0000] Downloading requests-2.22.0-py2.py3-none-any.whl (57 kB) 11:27:41 AM tlbu0: [17:27:12+0000] ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.0/58.0 KB 132.0 kB/s eta 0:00:00 11:27:41 AM tlbu0: [17:27:12+0000] Collecting requests_html==0.10.0 11:27:41 AM tlbu0: [17:27:12+0000] Downloading requests_html-0.10.0-py3-none-any.whl (13 kB) 11:27:41 AM tlbu0: [17:27:12+0000] Collecting cssmin==0.2.0 11:27:41 AM tlbu0: [17:27:12+0000] Downloading cssmin-0.2.0.tar.gz (3.2 kB) 11:27:41 AM tlbu0: [17:27:13+0000] Preparing metadata (setup.py): started 11:27:41 AM tlbu0: [17:27:13+0000] Preparing metadata (setup.py): finished with status 'done' 11:27:41 AM tlbu0: [17:27:13+0000] Collecting Werkzeug==2.0.0 11:27:41 AM tlbu0: [17:27:13+0000] Downloading Werkzeug-2.0.0-py3-none-any.whl (288 kB) 11:27:41 AM tlbu0: [17:27:13+0000] ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 288.1/288.1 KB 2.9 MB/s eta 0:00:00 11:27:41 AM tlbu0: [17:27:14+0000] Collecting WTForms==2.3.1 11:27:41 AM tlbu0: [17:27:14+0000] Downloading WTForms-2.3.1-py2.py3-none-any.whl (169 kB) 11:27:41 AM tlbu0: [17:27:14+0000] ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 169.1/169.1 KB 2.6 MB/s eta 0:00:00 11:27:41 AM tlbu0: [17:27:15+0000] Collecting SQLAlchemy==1.3.9 11:27:41 AM tlbu0: [17:27:15+0000] Downloading SQLAlchemy-1.3.9.tar.gz (6.0 MB) 11:27:41 AM tlbu0: [17:27:16+0000] ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 4.1 MB/s eta 0:00:00 11:27:41 AM tlbu0: [17:27:18+0000] Preparing metadata (setup.py): started 11:27:41 AM tlbu0: [17:27:20+0000] Preparing metadata (setup.py): finished with status 'done' 11:27:41 AM tlbu0: [17:27:20+0000] Collecting Flask==2.0.3 11:27:41 AM tlbu0: [17:27:20+0000] Downloading Flask-2.0.3-py3-none-any.whl (95 kB) 11:27:41 AM tlbu0: [17:27:20+0000] ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.6/95.6 KB 887.9 kB/s eta 0:00:00 11:27:41 AM tlbu0: [17:27:20+0000] Collecting jinja2==3.0.3 11:27:41 AM tlbu0: [17:27:20+0000] Downloading Jinja2-3.0.3-py3-none-any.whl (133 kB) 11:27:41 AM tlbu0: [17:27:20+0000] ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.6/133.6 KB 2.2 MB/s eta 0:00:00 11:27:41 AM tlbu0: [17:27:21+0000] Collecting click>=8.0.1 11:27:41 AM tlbu0: [17:27:21+0000] Downloading click-8.1.3-py3-none-any.whl (96 kB) 11:27:41 AM tlbu0: [17:27:21+0000] ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.6/96.6 KB 1.1 MB/s eta 0:00:00 11:27:42 AM tlbu0: [17:27:21+0000] Collecting Flask_Assets==2.0 11:27:42 AM tlbu0: [17:27:21+0000] Downloading Flask_Assets-2.0-py3-none-any.whl (8.5 kB) 11:27:42 AM tlbu0: [17:27:21+0000] Collecting flask-login==0.5.0 11:27:42 AM tlbu0: [17:27:21+0000] Downloading Flask_Login-0.5.0-py2.py3-none-any.whl (16 kB) 11:27:42 AM tlbu0: [17:27:22+0000] Collecting Flask_RESTful==0.3.9 11:27:42 AM tlbu0: [17:27:22+0000] Downloading Flask_RESTful-0.3.9-py2.py3-none-any.whl (25 kB) 11:27:42 AM tlbu0: [17:27:23+0000] Collecting Flask-Track-Usage==2.0.0 11:27:42 AM tlbu0: [17:27:23+0000] Downloading Flask-Track-Usage-2.0.0.tar.gz (37 kB) 11:27:42 AM tlbu0: [17:27:23+0000] Preparing metadata (setup.py): started 11:27:42 AM tlbu0: [17:27:39+0000] Preparing metadata (setup.py): finished with status 'error' 11:27:42 AM tlbu0: error: subprocess-exited-with-error 11:27:42 AM tlbu0:
11:27:42 AM tlbu0: × python setup.py egg_info did not run successfully. 11:27:42 AM tlbu0: │ exit code: 1 11:27:42 AM tlbu0: ╰─> [14 lines of output] 11:27:42 AM tlbu0: Traceback (most recent call last): 11:27:42 AM tlbu0: File "<string>", line 2, in <module> 11:27:42 AM tlbu0: File "<pip-setuptools-caller>", line 34, in <module> 11:27:42 AM tlbu0: File "/tmp/pip-install-9o0d_pdw/flask-track-usage_cbe6cf81d7a2455593cfdbd19c2e2fad/setup.py", line 38, in <module> 11:27:42 AM tlbu0: setup( 11:27:42 AM tlbu0: File "/tmp/8daf32fc4bbb7d4/antenv/lib/python3.9/site-packages/setuptools/init.py", line 152, in setup 11:27:42 AM tlbu0: _install_setup_requires(attrs) 11:27:42 AM tlbu0: File "/tmp/8daf32fc4bbb7d4/antenv/lib/python3.9/site-packages/setuptools/init.py", line 147, in _install_setup_requires 11:27:42 AM tlbu0: dist.fetch_build_eggs(dist.setup_requires) 11:27:42 AM tlbu0: File "/tmp/8daf32fc4bbb7d4/antenv/lib/python3.9/site-packages/setuptools/dist.py", line 806, in fetch_build_eggs 11:27:42 AM tlbu0: resolved_dists = pkg_resources.working_set.resolve( 11:27:42 AM tlbu0: File "/tmp/8daf32fc4bbb7d4/antenv/lib/python3.9/site-packages/pkg_resources/init.py", line 777, in resolve 11:27:42 AM tlbu0: raise VersionConflict(dist, req).with_context(dependent_req) 11:27:42 AM tlbu0: pkg_resources.ContextualVersionConflict: (sphinxcontrib.applehelp 1.0.3 (/tmp/pip-install-9o0d_pdw/flask-track-usage_cbe6cf81d7a2455593cfdbd19c2e2fad/.eggs/sphinxcontrib.applehelp-1.0.3-py3.9.egg), Requirement.parse('sphinxcontrib-applehelp'), {'sphinx'}) 11:27:42 AM tlbu0: [end of output] 11:27:42 AM tlbu0:
11:27:42 AM tlbu0: note: This error originates from a subprocess, and is likely not a problem with pip. 11:27:42 AM tlbu0: error: metadata-generation-failed 11:27:42 AM tlbu0: × Encountered error while generating package metadata. 11:27:42 AM tlbu0: ╰─> See above for output. 11:27:42 AM tlbu0: note: This is an issue with the package mentioned above, not pip. 11:27:42 AM tlbu0: hint: See above for details. 11:27:42 AM tlbu0: WARNING: You are using pip version 22.0.4; however, version 22.3.1 is available. 11:27:42 AM tlbu0: You should consider upgrading via the '/tmp/8daf32fc4bbb7d4/antenv/bin/python -m pip install --upgrade pip' command. 11:27:42 AM tlbu0: "2023-01-10 17:27:41"|ERROR|[17:27:12+0000] Collecting requests==2.22.0 11:27:42 AM tlbu0: [17:27:12+0000] Downloading requests-2.22.0-py2.py3-none-any.whl (57 kB) 11:27:42 AM tlbu0: [17:27:12+0000] ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.0/58.0 KB 132.0 kB/s eta 0:00:00 11:27:42 AM tlbu0: [17:27:12+0000] Collecting requests_html==0.10.0 11:27:42 AM tlbu0: [17:27:12+0000] Downloading requests_html-0.10.0-py3-none-any.whl (13 kB) 11:27:42 AM tlbu0: [17:27:12+0000] Collecting cssmin==0.2.0 11:27:42 AM tlbu0: [17:27:12+0000] Downloading cssmin-0.2.0.tar.gz (3.2 kB) 11:27:42 AM tlbu0: [17:27:13+0000] Preparing metadata (setup.py): started 11:27:42 AM tlbu0: [17:27:13+0000] Preparing metadata (setup.py): finished with status 'done' 11:27:42 AM tlbu0: [17:27:13+0000] Collecting Werkzeug==2.0.0 11:27:43 AM tlbu0: [17:27:13+0000] Downloading Werkzeug-2.0.0-py3-none-any.whl (288 kB) 11:27:43 AM tlbu0: [17:27:13+0000] ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 288.1/288.1 KB 2.9 MB/s eta 0:00:00 11:27:43 AM tlbu0: [17:27:14+0000] Collecting WTForms==2.3.1 11:27:43 AM tlbu0: [17:27:14+0000] Downloading WTForms-2.3.1-py2.py3-none-any.whl (169 kB) 11:27:43 AM tlbu0: [17:27:14+0000] ━━━━━━━���━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 169.1/169.1 KB 2.6 MB/s eta 0:00:00 11:27:43 AM tlbu0: [17:27:15+0000] Collecting SQLAlchemy==1.3.9 11:27:43 AM tlbu0: [17:27:15+0000] Downloading SQLAlchemy-1.3.9.tar.gz (6.0 MB) 11:27:43 AM tlbu0: [17:27:16+0000] ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 4.1 MB/s eta 0:00:00 11:27:43 AM tlbu0: [17:27:18+0000] Preparing metadata (setup.py): started 11:27:43 AM tlbu0: [17:27:20+0000] Preparing metadata (setup.py): finished with status 'done' 11:27:43 AM tlbu0: [17:27:20+0000] Collecting Flask==2.0.3 11:27:43 AM tlbu0: [17:27:20+0000] Downloading Flask-2.0.3-py3-none-any.whl (95 kB) 11:27:43 AM tlbu0: [17:27:20+0000] ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.6/95.6 KB 887.9 kB/s eta 0:00:00 11:27:43 AM tlbu0: [17:27:20+0000] Collecting jinja2==3.0.3 11:27:43 AM tlbu0: [17:27:20+0000] Downloading Jinja2-3.0.3-py3-none-any.whl (133 kB) 11:27:43 AM tlbu0: [17:27:20+0000] ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.6/133.6 KB 2.2 MB/s eta 0:00:00 11:27:43 AM tlbu0: [17:27:21+0000] Collecting click>=8.0.1 11:27:43 AM tlbu0: [17:27:21+0000] Downloading click-8.1.3-py3-none-any.whl (96 kB) 11:27:43 AM tlbu0: [17:27:21+0000] ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.6/96.6 KB 1.1 MB/s eta 0:00:00 11:27:43 AM tlbu0: [17:27:21+0000] Collecting Flask_Assets==2.0 11:27:43 AM tlbu0: [17:27:21+0000] Downloading Flask_Assets-2.0-py3-none-any.whl (8.5 kB) 11:27:43 AM tlbu0: [17:27:21+0000] Collecting flask-login==0.5.0 11:27:43 AM tlbu0: [17:27:21+0000] Downloading Flask_Login-0.5.0-py2.py3-none-any.whl (16 kB) 11:27:43 AM tlbu0: [17:27:22+0000] Collecting Flask_RESTful==0.3.9 11:27:43 AM tlbu0: [17:27:22+0000] Downloading Flask_RESTful-0.3.9-py2.py3-none-any.whl (25 kB) 11:27:43 AM tlbu0: [17:27:23+0000] Collecting Flask-Track-Usage==2.0.0 11:27:43 AM tlbu0: [17:27:23+0000] Downloading Flask-Track-Usage-2.0.0.tar.gz (37 kB) 11:27:43 AM tlbu0: [17:27:23+0000] Preparing metadata (setup.py): started 11:27:43 AM tlbu0: [17:27:39+0000] Preparing metadata (setup.py): finished with status 'error' 11:27:43 AM tlbu0: error: subprocess-exited-with-error 11:27:43 AM tlbu0:
11:27:43 AM tlbu0: × python setup.py egg_info did not run successfully. 11:27:43 AM tlbu0: │ exit code: 1 11:27:43 AM tlbu0: ╰─> [14 lines of output] 11:27:43 AM tlbu0: Traceback (most recent call last): 11:27:43 AM tlbu0: File "<string>", line 2, in <module> 11:27:43 AM tlbu0: File "<pip-setuptools-caller>", line 34, in <module> 11:27:43 AM tlbu0: File "/tmp/pip-install-9o0d_pdw/flask-track-usage_cbe6cf81d7a2455593cfdbd19c2e2fad/setup.py", line 38, in <module> 11:27:43 AM tlbu0: setup( 11:27:43 AM tlbu0: File "/tmp/8daf32fc4bbb7d4/antenv/lib/python3.9/site-packages/setuptools/init.py", line 152, in setup 11:27:43 AM tlbu0: _install_setup_requires(attrs) 11:27:43 AM tlbu0: File "/tmp/8daf32fc4bbb7d4/antenv/lib/python3.9/site-packages/setuptools/init.py", line 147, in _install_setup_requires 11:27:43 AM tlbu0: dist.fetch_build_eggs(dist.setup_requires) 11:27:43 AM tlbu0: File "/tmp/8daf32fc4bbb7d4/antenv/lib/python3.9/site-packages/setuptools/dist.py", line 806, in fetch_build_eggs 11:27:43 AM tlbu0: resolved_dists = pkg_resources.working_set.resolve( 11:27:44 AM tlbu0: File "/tmp/8daf32fc4bbb7d4/antenv/lib/python3.9/site-packages/pkg_resources/init.py", line 777, in resolve 11:27:44 AM tlbu0: raise VersionConflict(dist, req).with_context(dependent_req) 11:27:44 AM tlbu0: pkg_resources.ContextualVersionConflict: (sphinxcontrib.applehelp 1.0.3 (/tmp/pip-install-9o0d_pdw/flask-track-usage_cbe6cf81d7a2455593cfdbd19c2e2fad/.eggs/sphinxcontrib.applehelp-1.0.3-py3.9.egg), Requirement.parse('sphinxcontrib-applehelp'), {'sphinx'}) 11:27:44 AM tlbu0: [end of output] 11:27:44 AM tlbu0:
11:27:44 AM tlbu0: note: This error originates from a subprocess, and is likely not a problem with pip. 11:27:44 AM tlbu0: error: metadata-generation-failed 11:27:44 AM tlbu0: × Encountered error while generating package metadata. 11:27:44 AM tlbu0: ╰─> See above for output. 11:27:44 AM tlbu0: note: This is an issue with the package mentioned above, not pip. 11:27:44 AM tlbu0: hint: See above for details. 11:27:44 AM tlbu0: WARNING: You are using pip version 22.0.4; however, version 22.3.1 is available. 11:27:44 AM tlbu0: You should consider upgrading via the '/tmp/8daf32fc4bbb7d4/antenv/bin/python -m pip install --upgrade pip' command. | Exit code: 1 | Please review your requirements.txt | More information: https://aka.ms/troubleshoot-python 11:27:44 AM tlbu0: /bin/bash -c "oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform python --platform-version 3.9 -p virtualenv_name=antenv --log-file /tmp/build-debug.log -i /tmp/8daf32fc4bbb7d4 --compress-destination-dir | tee /tmp/oryx-build.log ; exit $PIPESTATUS " 11:27:44 AM tlbu0: Generating summary of Oryx build 11:27:44 AM tlbu0: Parsing the build logs 11:27:45 AM tlbu0: Found 1 issue(s) 11:27:45 AM tlbu0: Build Summary : 11:27:45 AM tlbu0: =============== 11:27:45 AM tlbu0: Errors (1) 11:27:45 AM tlbu0: 1. [17:27:12+0000] Collecting requests==2.22.0\n[17:27:12+0000] Downloading requests-2.22.0-py2.py3-none-any.whl (57 kB)\n[17:27:12+0000] ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.0/58.0 KB 132.0 kB/s eta 0:00:00\n[17:27:12+0000] Collecting requests_html==0.10.0\n[17:27:12+0000] Downloading requests_html-0.10.0-py3-none-any.whl (13 kB)\n[17:27:12+0000] Collecting cssmin==0.2.0\n[17:27:12+0000] Downloading cssmin-0.2.0.tar.gz (3.2 kB)\n[17:27:13+0000] Preparing metadata (setup.py): started\n[17:27:13+0000] Preparing metadata (setup.py): finished with status 'done'\n[17:27:13+0000] Collecting Werkzeug==2.0.0\n[17:27:13+0000] Downloading Werkzeug-2.0.0-py3-none-any.whl (288 kB)\n[17:27:13+0000] ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 288.1/288.1 KB 2.9 MB/s eta 0:00:00\n[17:27:14+0000] Collecting WTForms==2.3.1\n[17:27:14+0000] Downloading WTForms-2.3.1-py2.py3-none-any.whl (169 kB)\n[17:27:14+0000] ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 169.1/169.1 KB 2.6 MB/s eta 0:00:00\n[17:27:15+0000] Collecting SQLAlchemy==1.3.9\n[17:27:15+0000] Downloading SQLAlchemy-1.3.9.tar.gz (6.0 MB)\n[17:27:16+0000] ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 4.1 MB/s eta 0:00:00\n[17:27:18+0000] Preparing metadata (setup.py): started\n[17:27:20+0000] Preparing metadata (setup.py): finished with status 'done'\n[17:27:20+0000] Collecting Flask==2.0.3\n[17:27:20+0000] Downloading Flask-2.0.3-py3-none-any.whl (95 kB)\n[17:27:20+0000] ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.6/95.6 KB 887.9 kB/s eta 0:00:00\n[17:27:20+0000] Collecting jinja2==3.0.3\n[17:27:20+0000] Downloading Jinja2-3.0.3-py3-none-any.whl (133 kB)\n[17:27:20+0000] ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.6/133.6 KB 2.2 MB/s eta 0:00:00\n[17:27:21+0000] Collecting click>=8.0.1\n[17:27:21+0000] Downloading click-8.1.3-py3-none-any.whl (96 kB)\n[17:27:21+0000] ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.6/96.6 KB 1.1 MB/s eta 0:00:00\n[17:27:21+0000] Collecting Flask_Assets==2.0\n[17:27:21+0000] Downloading Flask_Assets-2.0-py3-none-any.whl (8.5 kB)\n[17:27:21+0000] Collecting flask-login==0.5.0\n[17:27:21+0000] Downloading Flask_Login-0.5.0-py2.py3-none-any.whl (16 kB)\n[17:27:22+0000] Collecting Flask_RESTful==0.3.9\n[17:27:22+0000] Downloading Flask_RESTful-0.3.9-py2.py3-none-any.whl (25 kB)\n[17:27:23+0000] Collecting Flask-Track-Usage==2.0.0\n[17:27:23+0000] Downloading Flask-Track-Usage-2.0.0.tar.gz (37 kB)\n[17:27:23+0000] Preparing metadata (setup.py): started\n[17:27:39+0000] Preparing metadata (setup.py): finished with status 'error'\n error: subprocess-exited-with-error\n \n × python setup.py egg_info did not run successfully.\n │ exit code: 1\n ╰─> [14 lines of output]\n Traceback (most recent call last):\n File "<string>", line 2, in <module>\n File "<pip-setuptools-caller>", line 34, in <module>\n File "/tmp/pip-install-9o0d_pdw/flask-track-usage_cbe6cf81d7a2455593cfdbd19c2e2fad/setup.py", line 38, in <module>\n setup(\n File "/tmp/8daf32fc4bbb7d4/antenv/lib/python3.9/site-packages/setuptools/init.py", line 152, in setup\n _install_setup_requires(attrs)\n File "/tmp/8daf32fc4bbb7d4/antenv/lib/python3.9/site-packages/setuptools/init.py", line 147, in _install_setup_requires\n dist.fetch_build_eggs(dist.setup_requires)\n File "/tmp/8daf32fc4bbb7d4/antenv/lib/python3.9/site-packages/setuptools/dist.py", line 806, in fetch_build_eggs\n resolved_dists = pkg_resources.working_set.resolve(\n File "/tmp/8daf32fc4bbb7d4/antenv/lib/python3.9/site-packages/pkg_resources/init.py", line 777, in resolve\n raise VersionConflict(dist, req).with_context(dependent_req)\n pkg_resources.ContextualVersionConflict: (sphinxcontrib.applehelp 1.0.3 (/tmp/pip-install-9o0d_pdw/flask-track-usage_cbe6cf81d7a2455593cfdbd19c2e2fad/.eggs/sphinxcontrib.applehelp-1.0.3-py3.9.egg), Requirement.parse('sphinxcontrib-applehelp'), {'sphinx'})\n [end of output]\n \n note: This error originates from a subprocess, and is likely not a problem with pip.\nerror: metadata-generation-failed\n\n× Encountered error while generating package metadata.\n╰─> See above for output.\n\nnote: This is an issue with the package mentioned above, not pip.\nhint: See above for details.\nWARNING: You are using pip version 22.0.4; however, version 22.3.1 is available.\nYou should consider upgrading via the '/tmp/8daf32fc4bbb7d4/antenv/bin/python -m pip install --upgrade pip' command.
11:27:45 AM tlbu0: - Next Steps: Please review your requirements.txt 11:27:45 AM tlbu0: - For more details you can browse to https://aka.ms/troubleshoot-python 11:27:45 AM tlbu0: Warnings (0) 11:27:46 AM tlbu0: Deployment Failed. deployer = Push-Deployer deploymentPath = ZipDeploy. Extract zip. Remote build. 11:28:00 AM tlbu0: Deployment failed.

**Comment by ashcrow** [comment]
Hi @josephdong8088. Thanks for the report! I'll take a look and try to reproduce the issue.

**Comment by ashcrow** [comment]
Taking a look at the output my first thought is that the failure is coming from `sphinxcontrib-applehelp`:

```
raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (sphinxcontrib.applehelp 1.0.3 
    (/tmp/pip-install-9o0d_pdw/flask-track-usage_cbe6cf81d7a2455593cfdbd19c2e2fa/.egg/sphinxcontrib.applehelp-1.0.3-py3.9.egg),
Requirement.parse('sphinxcontrib-applehelp'), {'sphinx'})
```

I was able to reproduce the issue you're seeing but it's somewhat perplexing. The issue happens when `setup.py` installs `sphinx`. However, if I run `pip install sphinx` _before_ I install `Flask-Track-Usage` then `sphinxcontrib-applehelp` doesn't fail. Maybe `egg` versus `whl`?

As a workaround you should be able to install `sphinx` before installing `Flask-Track-Usage`. Maybe it's time to move `sphinx` [out of setup_requires](https://github.com/ashcrow/flask-track-usage/blob/master/setup.py#L51-L53)

**Comment by josephdong8088** [comment]
Thank you @ashcrow for your prompt response. I have tested by adding `Sphinx` into my project before incorporating `Flask-Track-Usage`, but I encountered the same issue. I utilized Sphinx version 5.3.0, which may not be compatible with `Flask-Track-Usage.` Do you have any suggestions for a compatible version of Sphinx?

`11:50:07 AM tlbu0: [17:49:46+0000] Collecting sphinx==5.3.0

11:50:07 AM tlbu0: [17:49:46+0000]   Downloading sphinx-5.3.0-py3-none-any.whl (3.2 MB)
11:50:07 AM tlbu0: [17:49:46+0000]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 27.7 MB/s eta 0:00:00
11:50:07 AM tlbu0: [17:49:46+0000] Collecting Flask-Track-Usage==2.0.0
11:50:07 AM tlbu0: [17:49:46+0000]   Downloading Flask-Track-Usage-2.0.0.tar.gz (37 kB)
11:50:07 AM tlbu0: [17:49:46+0000]   Preparing metadata (setup.py): started
11:50:07 AM tlbu0: [17:49:58+0000]   Preparing metadata (setup.py): finished with status 'error'`
